# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
#RESPUESTA
import numpy as np


#### 2. Print your NumPy version.

In [4]:
#RESPUESTA
print(np.__version__)

1.23.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
a = np.random.rand(2,3,5)
print(a)

[[[0.61526896 0.76017765 0.50797715 0.93468761 0.70820072]
  [0.55798169 0.10298531 0.6374498  0.45924971 0.05444781]
  [0.17892304 0.09790997 0.91495434 0.37341665 0.36905863]]

 [[0.48502514 0.64672936 0.61316694 0.13974514 0.10380713]
  [0.52899801 0.11373726 0.78082968 0.26405525 0.31240051]
  [0.04130626 0.68957762 0.15914575 0.20585253 0.25530079]]]


In [6]:
# Method 2
b= np.random.random_sample((2,3,5))
print(b)

[[[0.42217073 0.82212805 0.84431763 0.01005204 0.57487319]
  [0.91708793 0.48261971 0.64373218 0.93999073 0.53571055]
  [0.00692055 0.04791963 0.06142041 0.15629291 0.27083917]]

 [[0.35443413 0.70890542 0.61954607 0.97452927 0.51697064]
  [0.6811621  0.33285159 0.80228549 0.79027899 0.02728469]
  [0.63292793 0.12574107 0.12601966 0.27716313 0.41619561]]]


In [7]:
# Method 3
c= np.random.randint(low=3,high=(100), size=(2, 3, 5))
print(c)
 #low es el número más bajo que permite y high elmás alto.


[[[58 95 91 67 95]
  [48 18  6 70 19]
  [23 97 59 41 44]]

 [[60 33 87 32 91]
  [58 74 22 29 77]
  [66 59 26 38  3]]]


In [8]:
np.arange(30).reshape(2,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

#### 4. Print *a*.


In [9]:
#RESPUESTA
print(a)

[[[0.61526896 0.76017765 0.50797715 0.93468761 0.70820072]
  [0.55798169 0.10298531 0.6374498  0.45924971 0.05444781]
  [0.17892304 0.09790997 0.91495434 0.37341665 0.36905863]]

 [[0.48502514 0.64672936 0.61316694 0.13974514 0.10380713]
  [0.52899801 0.11373726 0.78082968 0.26405525 0.31240051]
  [0.04130626 0.68957762 0.15914575 0.20585253 0.25530079]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [10]:
# ANSWER
b= np.ones((5,2,3))

#### 6. Print *b*.


In [11]:
# ANSWER
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [12]:
if a.size == b.size:
    print(True)
else:
    print(False)

#"a" and "b" have the same size


True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [13]:
#At first it would be not possible becasuse hvent got the same shape but if I do a.reshape, it is.
b_res= b.reshape(2,3,5)
arrays_sum = a + b_res
print(arrays_sum)


[[[1.61526896 1.76017765 1.50797715 1.93468761 1.70820072]
  [1.55798169 1.10298531 1.6374498  1.45924971 1.05444781]
  [1.17892304 1.09790997 1.91495434 1.37341665 1.36905863]]

 [[1.48502514 1.64672936 1.61316694 1.13974514 1.10380713]
  [1.52899801 1.11373726 1.78082968 1.26405525 1.31240051]
  [1.04130626 1.68957762 1.15914575 1.20585253 1.25530079]]]


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [14]:
# your code here
c= b.reshape(5,3,2).transpose()
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [15]:
# It works because both have the same shape. In the other case, I had to do reshape but here it is not necesary becase the transpose just above
d= a + c
print(d)

[[[1.61526896 1.76017765 1.50797715 1.93468761 1.70820072]
  [1.55798169 1.10298531 1.6374498  1.45924971 1.05444781]
  [1.17892304 1.09790997 1.91495434 1.37341665 1.36905863]]

 [[1.48502514 1.64672936 1.61316694 1.13974514 1.10380713]
  [1.52899801 1.11373726 1.78082968 1.26405525 1.31240051]
  [1.04130626 1.68957762 1.15914575 1.20585253 1.25530079]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [16]:
#the values of the elements in array "d" is the same that the values of array "a" adding 1.
print(a)
print(a.size)
print(d)
print(d.size)

[[[0.61526896 0.76017765 0.50797715 0.93468761 0.70820072]
  [0.55798169 0.10298531 0.6374498  0.45924971 0.05444781]
  [0.17892304 0.09790997 0.91495434 0.37341665 0.36905863]]

 [[0.48502514 0.64672936 0.61316694 0.13974514 0.10380713]
  [0.52899801 0.11373726 0.78082968 0.26405525 0.31240051]
  [0.04130626 0.68957762 0.15914575 0.20585253 0.25530079]]]
30
[[[1.61526896 1.76017765 1.50797715 1.93468761 1.70820072]
  [1.55798169 1.10298531 1.6374498  1.45924971 1.05444781]
  [1.17892304 1.09790997 1.91495434 1.37341665 1.36905863]]

 [[1.48502514 1.64672936 1.61316694 1.13974514 1.10380713]
  [1.52899801 1.11373726 1.78082968 1.26405525 1.31240051]
  [1.04130626 1.68957762 1.15914575 1.20585253 1.25530079]]]
30


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [17]:
# your code here
e= a*c
print(e)

[[[0.61526896 0.76017765 0.50797715 0.93468761 0.70820072]
  [0.55798169 0.10298531 0.6374498  0.45924971 0.05444781]
  [0.17892304 0.09790997 0.91495434 0.37341665 0.36905863]]

 [[0.48502514 0.64672936 0.61316694 0.13974514 0.10380713]
  [0.52899801 0.11373726 0.78082968 0.26405525 0.31240051]
  [0.04130626 0.68957762 0.15914575 0.20585253 0.25530079]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [18]:
# Yes because each element of "c" array values 1, so the product between a and c has the same value that "e".

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [52]:
print(d)
print(d.max())
print(d.min())
print(d.mean())

[[[1.61526896 1.76017765 1.50797715 1.93468761 1.70820072]
  [1.55798169 1.10298531 1.6374498  1.45924971 1.05444781]
  [1.17892304 1.09790997 1.91495434 1.37341665 1.36905863]]

 [[1.48502514 1.64672936 1.61316694 1.13974514 1.10380713]
  [1.52899801 1.11373726 1.78082968 1.26405525 1.31240051]
  [1.04130626 1.68957762 1.15914575 1.20585253 1.25530079]]]
1.9346876073137405
1.0413062649462308
1.4204122139672868


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [53]:
#Respuesta
f= np.empty((2,3,5))
print(f)

[[[1.61526896 1.76017765 1.50797715 1.93468761 1.70820072]
  [1.55798169 1.10298531 1.6374498  1.45924971 1.05444781]
  [1.17892304 1.09790997 1.91495434 1.37341665 1.36905863]]

 [[1.48502514 1.64672936 1.61316694 1.13974514 1.10380713]
  [1.52899801 1.11373726 1.78082968 1.26405525 1.31240051]
  [1.04130626 1.68957762 1.15914575 1.20585253 1.25530079]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [54]:
f= np.zeros((2,3,5))


In [71]:
# Lo he intentado hacer al inicio con un for, pero era inviable. Error en cada paso.
#Buscando he visto esta forma aunque no sé si es lo correcto, no estoy convenicida 

f = np.zeros((2, 3, 5))

f[np.where(d > d.min())] = 25
f[np.where(d < d.mean())] = 25
f[np.where(d > d.mean())] = 75
f[np.where(d < d.max())] = 75
f[np.where(d == d.mean())] = 50
f[np.where(d == d.min())] = 0
f[np.where(d == d.max())] = 100

print(f)

[[[ 75.  75.  75. 100.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]
  [  0.  75.  75.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [72]:
#Analizando los resultados sí que creo que son correctos. 
print(d)
print(f)

[[[1.61526896 1.76017765 1.50797715 1.93468761 1.70820072]
  [1.55798169 1.10298531 1.6374498  1.45924971 1.05444781]
  [1.17892304 1.09790997 1.91495434 1.37341665 1.36905863]]

 [[1.48502514 1.64672936 1.61316694 1.13974514 1.10380713]
  [1.52899801 1.11373726 1.78082968 1.26405525 1.31240051]
  [1.04130626 1.68957762 1.15914575 1.20585253 1.25530079]]]
[[[ 75.  75.  75. 100.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]
  [  0.  75.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [104]:
# Creo que es algo así, pero no me funciona bien porque los datos de mi matriz son diferentes.

f = f.astype(str)
f[f == ('75.')]= 'D'
f[f == ('100.0')]= 'B'
f[f == ('0.0')]= 'A'

print(f)

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'D' 'D' 'D']
  ['D' 'D' 'D' 'D' 'D']]

 [['D' 'D' 'D' 'D' 'D']
  ['D' 'D' 'D' 'D' 'D']
  ['A' 'D' 'D' 'D' 'D']]]
