# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [154]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [155]:
# your code here
np.__version__

'1.23.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [156]:
# Method 1
import random
a = np.array(random.sample(range(30), 30)).reshape(2,3,5)
print(a)

[[[ 6 27 15 14  4]
  [ 8 16  1  5  2]
  [ 7 10 12 24 26]]

 [[ 9  3 28 11 20]
  [21 13 19 23 22]
  [ 0 25 29 17 18]]]


In [157]:
# Method 2
a = np.array([random.randint(0,30) for i in range(30)]).reshape(2,3,5)
print(a)

[[[ 8  8 23  3  3]
  [13 30  2 27 17]
  [16 11  8 22 27]]

 [[27 14  5 20 24]
  [22 21 19  2 19]
  [10  6 29 11  4]]]


In [158]:
# Method 3
my_list = [[random.sample(range(30), 5), random.sample(range(30), 5), random.sample(range(30), 5)],[random.sample(range(30), 5), random.sample(range(30), 5), random.sample(range(30), 5)]]
print(my_list)
a = np.array(my_list)
print(a)
a.shape

[[[16, 25, 6, 21, 13], [3, 20, 16, 19, 6], [3, 11, 14, 2, 27]], [[2, 6, 22, 8, 23], [26, 9, 11, 20, 1], [25, 3, 2, 5, 24]]]
[[[16 25  6 21 13]
  [ 3 20 16 19  6]
  [ 3 11 14  2 27]]

 [[ 2  6 22  8 23]
  [26  9 11 20  1]
  [25  3  2  5 24]]]


(2, 3, 5)

#### 4. Print *a*.


In [159]:
# your code here
print(a)
print(a.shape)

[[[16 25  6 21 13]
  [ 3 20 16 19  6]
  [ 3 11 14  2 27]]

 [[ 2  6 22  8 23]
  [26  9 11 20  1]
  [25  3  2  5 24]]]
(2, 3, 5)


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [160]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [161]:
# your code here
print(b)
print(b.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
(5, 2, 3)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [162]:
# your code here
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [163]:
# your answer here
#c = a + b

print(a.shape)
print(b.shape)

# You cant, beause different shapes

(2, 3, 5)
(5, 2, 3)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [164]:
# your code here
c = b.reshape((2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [165]:
# your code/answer here
d = a + c
print(d)

[[[17. 26.  7. 22. 14.]
  [ 4. 21. 17. 20.  7.]
  [ 4. 12. 15.  3. 28.]]

 [[ 3.  7. 23.  9. 24.]
  [27. 10. 12. 21.  2.]
  [26.  4.  3.  6. 25.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [166]:
# your code/answer here
print(a)
print(d)

# All elements in array "a" are iqual to the elements in the same position on array "d" + 1, also de type value of each element vary. 

[[[16 25  6 21 13]
  [ 3 20 16 19  6]
  [ 3 11 14  2 27]]

 [[ 2  6 22  8 23]
  [26  9 11 20  1]
  [25  3  2  5 24]]]
[[[17. 26.  7. 22. 14.]
  [ 4. 21. 17. 20.  7.]
  [ 4. 12. 15.  3. 28.]]

 [[ 3.  7. 23.  9. 24.]
  [27. 10. 12. 21.  2.]
  [26.  4.  3.  6. 25.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [167]:
# your code here
e = a * c
print(e)

[[[16. 25.  6. 21. 13.]
  [ 3. 20. 16. 19.  6.]
  [ 3. 11. 14.  2. 27.]]

 [[ 2.  6. 22.  8. 23.]
  [26.  9. 11. 20.  1.]
  [25.  3.  2.  5. 24.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [168]:
# your code/answer here

# The have the same values, but different value types on each element, so they are not the same

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [169]:
# your code here
d_max = a[np.unravel_index(d.argmax(), d.shape)]
print(d_max)
d_min = a[np.unravel_index(d.argmin(), d.shape)]
print(d_min)
d_mean = d.mean()
print(d_mean)

27
1
13.966666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [170]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[16. 25.  6. 21. 13.]
  [ 3. 20. 16. 19.  6.]
  [ 3. 11. 14.  2. 27.]]

 [[ 2.  6. 22.  8. 23.]
  [26.  9. 11. 20.  1.]
  [25.  3.  2.  5. 24.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [171]:
# your code here
it = np.nditer(d, flags=['multi_index'])
for x in it:

    if (x == d_min):
        f[it.multi_index] = 0
    elif (x < d_mean):
        f[it.multi_index] = 25
    elif (x == d_mean):
        f[it.multi_index] = 50
    elif (x < d_max):
        f[it.multi_index] = 75
    else:
        f[it.multi_index] = 100
        
print(f)

[[[ 75.  75.  25.  75.  75.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  25.  75.  25. 100.]]

 [[ 25.  25.  75.  25.  75.]
  [100.  25.  25.  75.  25.]
  [ 75.  25.  25.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [172]:
# your code here
print(d)
print("\n")
print(f)

[[[17. 26.  7. 22. 14.]
  [ 4. 21. 17. 20.  7.]
  [ 4. 12. 15.  3. 28.]]

 [[ 3.  7. 23.  9. 24.]
  [27. 10. 12. 21.  2.]
  [26.  4.  3.  6. 25.]]]


[[[ 75.  75.  25.  75.  75.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  25.  75.  25. 100.]]

 [[ 25.  25.  75.  25.  75.]
  [100.  25.  25.  75.  25.]
  [ 75.  25.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [173]:
# your code here
i = 0
g = np.empty((2,3,5), dtype='object')
while i < 2:
    j = 0
    while j < 3:
        k = 0
        while k < 5:
            if (d[i,j,k] == d_min):
                g[i,j,k] = "A"
            elif (d[i,j,k] < d_mean):
                g[i,j,k] = "B"
            elif (d[i,j,k] == d_mean):
                g[i,j,k] = "C"
            elif (d[i,j,k] < d_max):
                g[i,j,k] = "D"
            else:
                g[i,j,k] = 'E'
            k += 1
        j += 1
    i += 1
    #if (i == 0):
    #    f[i] == "A"
    #elif (f[x] == 25):
    #    f[x] == "B"
    #elif (f[(x)] == 50):
    #    f[x] == "C"
    #elif (f[x] == 75):
    #    f[x] == "D"
    #if (f[x] == 100):
    #    f[x] == "E"
print(g)

[[['D' 'D' 'B' 'D' 'D']
  ['B' 'D' 'D' 'D' 'B']
  ['B' 'B' 'D' 'B' 'E']]

 [['B' 'B' 'D' 'B' 'D']
  ['E' 'B' 'B' 'D' 'B']
  ['D' 'B' 'B' 'B' 'D']]]
