# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [61]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [62]:
# your code here
np.__version__


'1.23.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [63]:
# Method 1
a = np.arange(30).reshape(2,3,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [64]:
# Method 2
a = np.random.rand(2, 3, 5)
a

array([[[0.32545054, 0.04126653, 0.98948457, 0.64865642, 0.32508049],
        [0.94808929, 0.40284932, 0.88467509, 0.0265644 , 0.55061131],
        [0.27851537, 0.90529184, 0.61920852, 0.14034329, 0.36185047]],

       [[0.10182752, 0.77607491, 0.66501167, 0.09222219, 0.67058259],
        [0.4986034 , 0.61500415, 0.37315991, 0.44720822, 0.96040687],
        [0.41626028, 0.9278826 , 0.48982485, 0.78509098, 0.4335734 ]]])

In [65]:
# Method 3
a = np.random.uniform(low=0, high=1, size=(2, 3, 5))
a

array([[[0.45229089, 0.10287763, 0.10401874, 0.97745279, 0.47587307],
        [0.67634466, 0.96611386, 0.03327258, 0.9834397 , 0.04822973],
        [0.21407142, 0.09143212, 0.21502139, 0.92386161, 0.69052555]],

       [[0.46194258, 0.3502103 , 0.37621948, 0.11768154, 0.94888756],
        [0.98682886, 0.51813543, 0.11005389, 0.8769725 , 0.48040744],
        [0.71129191, 0.63647608, 0.29449785, 0.15505421, 0.67520271]]])

#### 4. Print *a*.


In [66]:
# your code here
print(a)

[[[0.45229089 0.10287763 0.10401874 0.97745279 0.47587307]
  [0.67634466 0.96611386 0.03327258 0.9834397  0.04822973]
  [0.21407142 0.09143212 0.21502139 0.92386161 0.69052555]]

 [[0.46194258 0.3502103  0.37621948 0.11768154 0.94888756]
  [0.98682886 0.51813543 0.11005389 0.8769725  0.48040744]
  [0.71129191 0.63647608 0.29449785 0.15505421 0.67520271]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [67]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [68]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [69]:
# your code here
if a == b:
    print('true')
else:
    print('false')
    
#No, no tienen el mismo tamaño

false


C:\Users\marym\AppData\Local\Temp\ipykernel_18468\3691629779.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if a == b:


#### 8. Are you able to add *a* and *b*? Why or why not?


In [70]:
# your answer here
c = a + b
c

#No, no se pueden, tienen que tener la misma distribución

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [71]:
# your code here
c = b.transpose((1, 2, 0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [72]:
# your code/answer here
d= sum(a,c)
d


array([[[1.91423347, 1.45308793, 1.48023822, 2.09513433, 2.42476063],
        [2.66317352, 2.48424929, 1.14332647, 2.86041219, 1.52863716],
        [1.92536333, 1.7279082 , 1.50951925, 2.07891582, 2.36572827]],

       [[1.91423347, 1.45308793, 1.48023822, 2.09513433, 2.42476063],
        [2.66317352, 2.48424929, 1.14332647, 2.86041219, 1.52863716],
        [1.92536333, 1.7279082 , 1.50951925, 2.07891582, 2.36572827]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [73]:
# your code/answer here
print(a)
print('-----------------------------------------------------')
print(d)
#No entiendo. La primera es a y la segunda son valores mayores por ser la suma de c + a

[[[0.45229089 0.10287763 0.10401874 0.97745279 0.47587307]
  [0.67634466 0.96611386 0.03327258 0.9834397  0.04822973]
  [0.21407142 0.09143212 0.21502139 0.92386161 0.69052555]]

 [[0.46194258 0.3502103  0.37621948 0.11768154 0.94888756]
  [0.98682886 0.51813543 0.11005389 0.8769725  0.48040744]
  [0.71129191 0.63647608 0.29449785 0.15505421 0.67520271]]]
-----------------------------------------------------
[[[1.91423347 1.45308793 1.48023822 2.09513433 2.42476063]
  [2.66317352 2.48424929 1.14332647 2.86041219 1.52863716]
  [1.92536333 1.7279082  1.50951925 2.07891582 2.36572827]]

 [[1.91423347 1.45308793 1.48023822 2.09513433 2.42476063]
  [2.66317352 2.48424929 1.14332647 2.86041219 1.52863716]
  [1.92536333 1.7279082  1.50951925 2.07891582 2.36572827]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [74]:
# your code here
e = a*c
e

array([[[0.45229089, 0.10287763, 0.10401874, 0.97745279, 0.47587307],
        [0.67634466, 0.96611386, 0.03327258, 0.9834397 , 0.04822973],
        [0.21407142, 0.09143212, 0.21502139, 0.92386161, 0.69052555]],

       [[0.46194258, 0.3502103 , 0.37621948, 0.11768154, 0.94888756],
        [0.98682886, 0.51813543, 0.11005389, 0.8769725 , 0.48040744],
        [0.71129191, 0.63647608, 0.29449785, 0.15505421, 0.67520271]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [75]:
# your code/answer here
print(type(e))
print(type(a))
#Sí, las dos son arrays de numpy

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [76]:
# your code here
d_max = np.max(d)
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

2.8604121935369995
1.1433264713131042
1.9769792057956186


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [78]:
# your code here
f=np.empty([2,3,5])
print(type(f))
f



<class 'numpy.ndarray'>


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [80]:
for i in d:
    print(i)

[[1.91423347 1.45308793 1.48023822 2.09513433 2.42476063]
 [2.66317352 2.48424929 1.14332647 2.86041219 1.52863716]
 [1.92536333 1.7279082  1.50951925 2.07891582 2.36572827]]
[[1.91423347 1.45308793 1.48023822 2.09513433 2.42476063]
 [2.66317352 2.48424929 1.14332647 2.86041219 1.52863716]
 [1.92536333 1.7279082  1.50951925 2.07891582 2.36572827]]


In [107]:
# your code here

d_max = np.max(d)
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)


for i in d:
    if i == d_max:
        f.append[i] = 100

    
'''elif d[(d<d_mean) | (d>d_min)]:
    d[25]
else d[(d>d_mean)| (d<d_max)]:
    d[75]
'''
        
print(f)
#Nada, no hay manera, me vuelvo loco probando y buscando

100.0
1.1433264713131042
8.452951726226486


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here