# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.23.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.randint(30,size=(2,3,5))

In [4]:
# Method 2
a = np.random.rand(2,3,5)

In [5]:
# Method 3
a = np.random.choice(range(100000), size=(2,3,5))

#### 4. Print *a*.


In [6]:
# your code here
a

array([[[86324, 82690,  6442, 72956, 82380],
        [43086, 91499, 78789, 50976, 65918],
        [27558, 91132, 94656, 12890, 27407]],

       [[85886, 24422, 64586,  2226,  4320],
        [96397, 16374, 81265, 32384, 83160],
        [47104, 39737, 50112, 84249, 75858]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
# changed to 5x3x2
b = np.ones((5,3,2))

#### 6. Print *b*.


In [8]:
# your code here
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

a.itemsize == b.itemsize

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = b.transpose()
np.shape(c)

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here

d = a + c
d

array([[[86325., 82691.,  6443., 72957., 82381.],
        [43087., 91500., 78790., 50977., 65919.],
        [27559., 91133., 94657., 12891., 27408.]],

       [[85887., 24423., 64587.,  2227.,  4321.],
        [96398., 16375., 81266., 32385., 83161.],
        [47105., 39738., 50113., 84250., 75859.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

print(a)
print(d)

#The addition of a and c executes on each value of the array, being a difference of 1 between each value of d and a

[[[86324 82690  6442 72956 82380]
  [43086 91499 78789 50976 65918]
  [27558 91132 94656 12890 27407]]

 [[85886 24422 64586  2226  4320]
  [96397 16374 81265 32384 83160]
  [47104 39737 50112 84249 75858]]]
[[[86325. 82691.  6443. 72957. 82381.]
  [43087. 91500. 78790. 50977. 65919.]
  [27559. 91133. 94657. 12891. 27408.]]

 [[85887. 24423. 64587.  2227.  4321.]
  [96398. 16375. 81266. 32385. 83161.]
  [47105. 39738. 50113. 84250. 75859.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

e == a
#They are equal since each value of a was multiplied by 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [29]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

96398.0
2227.0
56760.433333333334


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [22]:
# your code here

f = np.empty((2, 3, 5))
f

array([[[86325., 82691.,  6443., 72957., 82381.],
        [43087., 91500., 78790., 50977., 65919.],
        [27559., 91133., 94657., 12891., 27408.]],

       [[85887., 24423., 64587.,  2227.,  4321.],
        [96398., 16375., 81266., 32385., 83161.],
        [47105., 39738., 50113., 84250., 75859.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [35]:
# your code here

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            elif d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i, j, k] = 25
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i, j, k] = 75
            elif d[i,j,k] == d_mean:
                f[i, j, k] = 50
            elif d[i,j,k] == d_min:
                f[i, j, k] = 0
            elif d[i,j,k] == d_max:
                f[i, j, k] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [36]:
# your code here

print(d)
print(f)

[[[86325. 82691.  6443. 72957. 82381.]
  [43087. 91500. 78790. 50977. 65919.]
  [27559. 91133. 94657. 12891. 27408.]]

 [[85887. 24423. 64587.  2227.  4321.]
  [96398. 16375. 81266. 32385. 83161.]
  [47105. 39738. 50113. 84250. 75859.]]]
[[[ 75.  75.  25.  75.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 25.  75.  75.  25.  25.]]

 [[ 75.  25.  75.   0.  25.]
  [100.  25.  75.  25.  75.]
  [ 25.  25.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [44]:
# your code here

f = np.empty((2,3,5), dtype='U')

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i, j, k] = "B"
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i, j, k] = "D"
            elif d[i,j,k] == d_mean:
                f[i, j, k] = "C"
            elif d[i,j,k] == d_min:
                f[i, j, k] = "A"
            elif d[i,j,k] == d_max:
                f[i, j, k] = "E"

print(f)

[[['D' 'D' 'B' 'D' 'D']
  ['B' 'D' 'D' 'B' 'D']
  ['B' 'D' 'D' 'B' 'B']]

 [['D' 'B' 'D' 'A' 'B']
  ['E' 'B' 'D' 'B' 'D']
  ['B' 'B' 'B' 'D' 'D']]]
