# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [4]:
import numpy as np

#### 2. Print your NumPy version.

In [5]:
print(np.__version__)

1.23.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
a = np.random.randint(100, size = (2, 3, 5))
print(a)

[[[28 78 51 36 35]
  [97  6  7 65 79]
  [94 72 70 41 52]]

 [[75 25 35 30 53]
  [51  9 70  2 42]
  [44 48  8 18 74]]]


In [7]:
a.shape

(2, 3, 5)

In [8]:
a2 = np.random.rand(2, 3, 5)
print(a2)

[[[0.82319088 0.94956971 0.42724494 0.49086614 0.98625505]
  [0.80522171 0.70727701 0.96300021 0.77638997 0.58128652]
  [0.10055212 0.93551997 0.8300354  0.9306534  0.95502096]]

 [[0.00317443 0.44509238 0.94761111 0.32077744 0.27731132]
  [0.7277482  0.26731087 0.28283627 0.20412707 0.71872058]
  [0.52233633 0.71918546 0.98791763 0.17353    0.74461124]]]


In [9]:
a3 = np.random.choice(100, size = (2, 3, 5))
print(a3)

[[[44 67 28 20 73]
  [32 30 22 94 69]
  [53 72 83 81 19]]

 [[39 30 88 10  7]
  [63 68 14 46  1]
  [80 31 13 19 89]]]


#### 4. Print *a*.


In [10]:
print(a)

[[[28 78 51 36 35]
  [97  6  7 65 79]
  [94 72 70 41 52]]

 [[75 25 35 30 53]
  [51  9 70  2 42]
  [44 48  8 18 74]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [11]:
b = np.ones((5, 2, 3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [12]:
b.shape

(5, 2, 3)

#### 6. Print *b*.


In [13]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [14]:
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [15]:
#No, they don't have the same shape
c = np.add(a, b)
print(c)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [16]:
b.shape

(5, 2, 3)

In [17]:
c = b.reshape(2, 3, 5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [18]:
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [19]:
d = a + c
print(d)

[[[29. 79. 52. 37. 36.]
  [98.  7.  8. 66. 80.]
  [95. 73. 71. 42. 53.]]

 [[76. 26. 36. 31. 54.]
  [52. 10. 71.  3. 43.]
  [45. 49.  9. 19. 75.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [20]:
print(a)
print(d)

[[[28 78 51 36 35]
  [97  6  7 65 79]
  [94 72 70 41 52]]

 [[75 25 35 30 53]
  [51  9 70  2 42]
  [44 48  8 18 74]]]
[[[29. 79. 52. 37. 36.]
  [98.  7.  8. 66. 80.]
  [95. 73. 71. 42. 53.]]

 [[76. 26. 36. 31. 54.]
  [52. 10. 71.  3. 43.]
  [45. 49.  9. 19. 75.]]]


In [ ]:
#d is the same as a + 1 in every number
#this is because we added b, which was al ones
#nevertheless, now d are floats and not integers

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [21]:
e = a * c
print(e)

[[[28. 78. 51. 36. 35.]
  [97.  6.  7. 65. 79.]
  [94. 72. 70. 41. 52.]]

 [[75. 25. 35. 30. 53.]
  [51.  9. 70.  2. 42.]
  [44. 48.  8. 18. 74.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
#Yes, they are equal, because we
#are multiplying every number by one
#which result is the same number
#nevertheless, now e are floats and not integers

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [23]:
d_max = np.max(d)
print(d_max)

98.0


In [24]:
d_min = np.min(d)
print(d_min)

3.0


In [25]:
d_mean = np.mean(d)
print(d_mean)

47.5


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [41]:
f = np.empty([2,3,5])
type(f)

numpy.ndarray

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [65]:
f_list = []
for x in d:
    for y in x:
        for z in y:
            if z == d_mean:
                f_list.append(50)
            elif z == d_min:
                f_list.append(0)
            elif z == d_max:
                f_list.append(100)
            elif z < d_mean:
                f_list.append(25)
            elif z > d_mean:
                f_list.append(75)             
f_array = np.array(f_list)
f = f_array.reshape(2,3,5)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [66]:
print(d)

[[[29. 79. 52. 37. 36.]
  [98.  7.  8. 66. 80.]
  [95. 73. 71. 42. 53.]]

 [[76. 26. 36. 31. 54.]
  [52. 10. 71.  3. 43.]
  [45. 49.  9. 19. 75.]]]


In [67]:
print(f)

[[[ 25  75  75  25  25]
  [100  25  25  75  75]
  [ 75  75  75  25  75]]

 [[ 75  25  25  25  75]
  [ 75  25  75   0  25]
  [ 25  75  25  25  75]]]


In [ ]:
#I have the correct result, but I didn't know
#how to do it with the empty array, so I did it my way

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [69]:
f_list = []
for x in d:
    for y in x:
        for z in y:
            if z == d_mean:
                f_list.append("C")
            elif z == d_min:
                f_list.append("A")
            elif z == d_max:
                f_list.append("E")
            elif z < d_mean:
                f_list.append("B")
            elif z > d_mean:
                f_list.append("D")             
f_array = np.array(f_list)
f = f_array.reshape(2,3,5)
print(f)

[[['B' 'D' 'D' 'B' 'B']
  ['E' 'B' 'B' 'D' 'D']
  ['D' 'D' 'D' 'B' 'D']]

 [['D' 'B' 'B' 'B' 'D']
  ['D' 'B' 'D' 'A' 'B']
  ['B' 'D' 'B' 'B' 'D']]]
