# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [47]:
import numpy as np

#### 2. Print your NumPy version.

In [48]:
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [63]:
a = np.random.rand(2, 3, 5)

In [119]:
a = np.random.rand(2, 3, 5)

In [117]:
a = np.random.choice([500], size=(2, 3, 5))

#### 4. Print *a*.


In [120]:
a

array([[[0.040753  , 0.39007565, 0.85560864, 0.60810123, 0.09044812],
        [0.32349095, 0.47783751, 0.65895786, 0.30770757, 0.05138109],
        [0.27640582, 0.93053493, 0.97027188, 0.89137871, 0.72843804]],

       [[0.45808271, 0.07779267, 0.104646  , 0.44444666, 0.22097269],
        [0.63930843, 0.45317695, 0.43388517, 0.23031549, 0.77452618],
        [0.42363885, 0.56180577, 0.27523413, 0.34850132, 0.24997353]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [121]:
b = np.ones((5, 3, 2))

#### 6. Print *b*.


In [122]:
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [123]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [124]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [125]:
c = b.transpose()
np.shape(c)

print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [126]:
d = a + c

d

array([[[1.040753  , 1.39007565, 1.85560864, 1.60810123, 1.09044812],
        [1.32349095, 1.47783751, 1.65895786, 1.30770757, 1.05138109],
        [1.27640582, 1.93053493, 1.97027188, 1.89137871, 1.72843804]],

       [[1.45808271, 1.07779267, 1.104646  , 1.44444666, 1.22097269],
        [1.63930843, 1.45317695, 1.43388517, 1.23031549, 1.77452618],
        [1.42363885, 1.56180577, 1.27523413, 1.34850132, 1.24997353]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [127]:
print(a)

print(d)

#When you add a + d both arrays are combined having as a result the ones (1) added to the 500

[[[0.040753   0.39007565 0.85560864 0.60810123 0.09044812]
  [0.32349095 0.47783751 0.65895786 0.30770757 0.05138109]
  [0.27640582 0.93053493 0.97027188 0.89137871 0.72843804]]

 [[0.45808271 0.07779267 0.104646   0.44444666 0.22097269]
  [0.63930843 0.45317695 0.43388517 0.23031549 0.77452618]
  [0.42363885 0.56180577 0.27523413 0.34850132 0.24997353]]]
[[[1.040753   1.39007565 1.85560864 1.60810123 1.09044812]
  [1.32349095 1.47783751 1.65895786 1.30770757 1.05138109]
  [1.27640582 1.93053493 1.97027188 1.89137871 1.72843804]]

 [[1.45808271 1.07779267 1.104646   1.44444666 1.22097269]
  [1.63930843 1.45317695 1.43388517 1.23031549 1.77452618]
  [1.42363885 1.56180577 1.27523413 1.34850132 1.24997353]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [128]:
e = a * c

print(e)

[[[0.040753   0.39007565 0.85560864 0.60810123 0.09044812]
  [0.32349095 0.47783751 0.65895786 0.30770757 0.05138109]
  [0.27640582 0.93053493 0.97027188 0.89137871 0.72843804]]

 [[0.45808271 0.07779267 0.104646   0.44444666 0.22097269]
  [0.63930843 0.45317695 0.43388517 0.23031549 0.77452618]
  [0.42363885 0.56180577 0.27523413 0.34850132 0.24997353]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [129]:
e == a

#If you multiply a * c you will multiply 500 for each 1, so the result will be 500, having as a result the same array e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [136]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9702718806022483
1.0407530000151284
1.4432565854183357


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [137]:
f = np.empty([2, 3, 5])
f

array([[[0.040753  , 0.39007565, 0.85560864, 0.60810123, 0.09044812],
        [0.32349095, 0.47783751, 0.65895786, 0.30770757, 0.05138109],
        [0.27640582, 0.93053493, 0.97027188, 0.89137871, 0.72843804]],

       [[0.45808271, 0.07779267, 0.104646  , 0.44444666, 0.22097269],
        [0.63930843, 0.45317695, 0.43388517, 0.23031549, 0.77452618],
        [0.42363885, 0.56180577, 0.27523413, 0.34850132, 0.24997353]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [182]:
list_f = []

for values in d:
    for i in x:
        for z in y:
            if z == d_mean:
                list_f.append(50)
            elif z == d_min:
                list_f.append(0)
            elif z == d_max:
                list_f.append(100)
            elif z < d_mean:
                list_f.append(25)
            elif z > d_mean:
                list_f.append(75) 
                
f_array = np.array(list_f)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [184]:
print(d)

print(f)

#No sé que estoy haciendo mal aquí

[[[1.040753   1.39007565 1.85560864 1.60810123 1.09044812]
  [1.32349095 1.47783751 1.65895786 1.30770757 1.05138109]
  [1.27640582 1.93053493 1.97027188 1.89137871 1.72843804]]

 [[1.45808271 1.07779267 1.104646   1.44444666 1.22097269]
  [1.63930843 1.45317695 1.43388517 1.23031549 1.77452618]
  [1.42363885 1.56180577 1.27523413 1.34850132 1.24997353]]]
[[[25 75 25 25 25]
  [25 75 25 25 25]
  [25 75 25 25 25]]

 [[25 75 25 25 25]
  [25 75 25 25 25]
  [25 75 25 25 25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [193]:
herelist_f = []

for values in d:
    for i in x:
        for z in y:
            if z == d_mean:
                herelist_f.append("C")
            elif z == d_min:
                herelist_f.append("A")
            elif z == d_max:
                herelist_f.append("E")
            elif z < d_mean:
                herelist_f.append("B")
            elif z > d_mean:
                herelist_f.append("D") 
                
f_array = np.array(herelist_f)
herelist_f = f_array.reshape(2,3,5)

herelist_f

array([[['B', 'D', 'B', 'B', 'B'],
        ['B', 'D', 'B', 'B', 'B'],
        ['B', 'D', 'B', 'B', 'B']],

       [['B', 'D', 'B', 'B', 'B'],
        ['B', 'D', 'B', 'B', 'B'],
        ['B', 'D', 'B', 'B', 'B']]], dtype='<U1')