# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [234]:
import numpy as np

#### 2. Print your NumPy version.

In [235]:
print(np.__version__)

1.23.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [236]:
import numpy as np
x = np.random.random((2,3,5))
print(x)

[[[0.99326784 0.80073407 0.03050456 0.78250982 0.00993442]
  [0.25776869 0.47517579 0.7987615  0.8376821  0.23390843]
  [0.26119759 0.63967317 0.39310137 0.36201798 0.54385149]]

 [[0.77884222 0.15985102 0.33761668 0.98649236 0.25393941]
  [0.83709971 0.57364586 0.87145022 0.12422796 0.6525694 ]
  [0.36060826 0.55630862 0.70401125 0.27467315 0.88920905]]]


In [237]:
import numpy as np
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [238]:
a=np.arange(30).reshape(2,3,5)

#### 4. Print *a*.


In [239]:
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [240]:
import numpy as np
b = np.ones((5,2,3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 6. Print *b*.


In [244]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [242]:
print(a.size, b.size)

30 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [243]:
(a + b) different shapes

SyntaxError: invalid syntax (1213614638.py, line 1)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [245]:
c = np.transpose(b, (1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [252]:
d = (a + c)
print(d)

[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]
  [11. 12. 13. 14. 15.]]

 [[16. 17. 18. 19. 20.]
  [21. 22. 23. 24. 25.]
  [26. 27. 28. 29. 30.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [256]:
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [257]:
print(d) float 

[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]
  [11. 12. 13. 14. 15.]]

 [[16. 17. 18. 19. 20.]
  [21. 22. 23. 24. 25.]
  [26. 27. 28. 29. 30.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [262]:
e = a * c
print(e)

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]]

 [[15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [263]:
no! e = float and a = int

SyntaxError: invalid syntax (2197340712.py, line 1)

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [269]:
d_max = d.max()
print(d_max)

d_min = d.min()
print(d_min)

d_mean = d.mean()
print(d_mean)

30.0
1.0
15.5


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [274]:
f = np.empty([2, 3, 5])
print(f)

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]]

 [[15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [303]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            value = d[i][j][k]
            
            if value > d_min and value < d_mean:
                f[i][j][k] = 25
            elif value > d_min and value < d_max:
                f[i][j][k] = 75
            elif value == d_mean:
                f[i][j][k] = 50
            elif value == d_min:
                f[i][j][k] = 0
            elif value == d_max:
                f[i][j][k] = 100
print(f)

[[[  0.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75. 100.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [309]:
new_d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

new_f = np.empty([2, 3, 5])
new_d_min = new_d.min()
new_d_max = new_d.max()
new_d_mean = new_d.mean()

for i in range(2):
    for j in range(3):
        for k in range(5):
            value = new_d[i][j][k]
            
            if value > new_d_min and value < new_d_mean:
                new_f[i][j][k] = 25
            elif value > new_d_min and value < new_d_max:
                new_f[i][j][k] = 75
            elif value == new_d_mean:
                new_f[i][j][k] = 50
            elif value == new_d_min:
                new_f[i][j][k] = 0
            elif value == new_d_max:
                new_f[i][j][k] = 100
print(new_f)

[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [320]:
new_f_2 = np.empty([2, 3, 5], dtype=object)

for i in range(2):
    for j in range(3):
        for k in range(5):
            value = new_d[i][j][k]
            
            if value > new_d_min and value < new_d_mean:
                new_f_2[i][j][k] = 'B'
            elif value > new_d_min and value < new_d_max:
                new_f_2[i][j][k] = 'D'
            elif value == new_d_mean:
                new_f_2[i][j][k] = 'C'
            elif value == new_d_min:
                new_f_2[i][j][k] = 'A'
            elif value == new_d_max:
                new_f_2[i][j][k] = 'E'
print(new_f_2)

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]


In [323]:
def queue_time(customers, n):
    tills = [0]*n
    for i in customers:
      tills[0] += i
      tills.sort()
    return max(tills)