# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.23.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.random((2,3,5))

In [15]:
# Method 2
a = np.random.randint(10, size = (2,3,5))

In [16]:
# Method 3
a = np.random.rand(2,3,5)

#### 4. Print *a*.


In [96]:
# your code here
a

array([[[0.10561236, 0.97188464, 0.32358858, 0.96321504, 0.18297856],
        [0.93668579, 0.9777151 , 0.04040853, 0.43660165, 0.51956401],
        [0.03032517, 0.52191316, 0.29988061, 0.9161468 , 0.51076535]],

       [[0.4744228 , 0.14141182, 0.532743  , 0.99444281, 0.26297436],
        [0.37304607, 0.92998851, 0.50572288, 0.75889627, 0.52175164],
        [0.90298382, 0.03067007, 0.26504612, 0.0253452 , 0.27199935]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [25]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [34]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [29]:
# your code here
a.size
b.size

a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [9]:
# your answer here
np.add (a,b)

# We can't because a and b has differents shapes.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [35]:
# your code here
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [36]:
# your code/answer here
d = np.add (a,c)

print(a.shape)
print(c.shape)

#Because now they have the same shape.

(2, 3, 5)
(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [37]:
# your code/answer here
print('A')
print(a)
print('D')
print(d)

# In B we sum 1 to every element of the A array.

A
[[[0.10561236 0.97188464 0.32358858 0.96321504 0.18297856]
  [0.93668579 0.9777151  0.04040853 0.43660165 0.51956401]
  [0.03032517 0.52191316 0.29988061 0.9161468  0.51076535]]

 [[0.4744228  0.14141182 0.532743   0.99444281 0.26297436]
  [0.37304607 0.92998851 0.50572288 0.75889627 0.52175164]
  [0.90298382 0.03067007 0.26504612 0.0253452  0.27199935]]]
D
[[[1.10561236 1.97188464 1.32358858 1.96321504 1.18297856]
  [1.93668579 1.9777151  1.04040853 1.43660165 1.51956401]
  [1.03032517 1.52191316 1.29988061 1.9161468  1.51076535]]

 [[1.4744228  1.14141182 1.532743   1.99444281 1.26297436]
  [1.37304607 1.92998851 1.50572288 1.75889627 1.52175164]
  [1.90298382 1.03067007 1.26504612 1.0253452  1.27199935]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [52]:
# your code here
e = np.multiply(a,c)
e

array([[[0.10561236, 0.97188464, 0.32358858, 0.96321504, 0.18297856],
        [0.93668579, 0.9777151 , 0.04040853, 0.43660165, 0.51956401],
        [0.03032517, 0.52191316, 0.29988061, 0.9161468 , 0.51076535]],

       [[0.4744228 , 0.14141182, 0.532743  , 0.99444281, 0.26297436],
        [0.37304607, 0.92998851, 0.50572288, 0.75889627, 0.52175164],
        [0.90298382, 0.03067007, 0.26504612, 0.0253452 , 0.27199935]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [53]:
# your code/answer here

e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [83]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print('MAX',' ',d_max)
print('MIN',' ',d_min)
print('MEAN',' ',d_mean)

MAX   1.994442809537493
MIN   1.0253452037475026
MEAN   1.4909576694651554


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [55]:
# your code here
f = np.empty((2,3,5))
f

array([[[0.10561236, 0.97188464, 0.32358858, 0.96321504, 0.18297856],
        [0.93668579, 0.9777151 , 0.04040853, 0.43660165, 0.51956401],
        [0.03032517, 0.52191316, 0.29988061, 0.9161468 , 0.51076535]],

       [[0.4744228 , 0.14141182, 0.532743  , 0.99444281, 0.26297436],
        [0.37304607, 0.92998851, 0.50572288, 0.75889627, 0.52175164],
        [0.90298382, 0.03067007, 0.26504612, 0.0253452 , 0.27199935]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [92]:
f = np.zeros_like(d)

f[(d > d_min) & (d < d_mean)] = 25
f[d == d_mean] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_min] = 0
f[d == d_max] = 100
f

array([[[ 25.,  75.,  25.,  75.,  25.],
        [ 75.,  75.,  25.,  25.,  75.],
        [ 25.,  75.,  25.,  75.,  75.]],

       [[ 25.,  25.,  75., 100.,  25.],
        [ 25.,  75.,  75.,  75.,  75.],
        [ 75.,  25.,  25.,   0.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [91]:
print('D')
print(d)
print('F')
print(f)

D
[[[1.10561236 1.97188464 1.32358858 1.96321504 1.18297856]
  [1.93668579 1.9777151  1.04040853 1.43660165 1.51956401]
  [1.03032517 1.52191316 1.29988061 1.9161468  1.51076535]]

 [[1.4744228  1.14141182 1.532743   1.99444281 1.26297436]
  [1.37304607 1.92998851 1.50572288 1.75889627 1.52175164]
  [1.90298382 1.03067007 1.26504612 1.0253452  1.27199935]]]
F
[[[ 25  75  25  75  25]
  [ 75  75  25  25  75]
  [ 25  75  25  75  75]]

 [[ 25  25  75 100  25]
  [ 25  75  75  75  75]
  [ 75  25  25   0  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [95]:
g = np.empty((2, 3, 5), dtype=str)

g[(d > d_min) & (d < d_mean)] = 'A'
g[d == d_mean] = 'B'
g[(d > d_mean) & (d < d_max)] = 'C'
g[d == d_min] = 'D'
g[d == d_max] = 'E'
g

array([[['A', 'C', 'A', 'C', 'A'],
        ['C', 'C', 'A', 'A', 'C'],
        ['A', 'C', 'A', 'C', 'C']],

       [['A', 'A', 'C', 'E', 'A'],
        ['A', 'C', 'C', 'C', 'C'],
        ['C', 'A', 'A', 'D', 'A']]], dtype='<U1')