# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.23.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random((2,3,5))
print(a)

[[[0.11226568 0.8973345  0.75927893 0.27296176 0.23321398]
  [0.69649753 0.59929898 0.41886666 0.43849722 0.28543532]
  [0.59080318 0.02979872 0.67780113 0.62811983 0.03007618]]

 [[0.62068285 0.47056242 0.87764528 0.60030138 0.52070466]
  [0.19975772 0.35854492 0.86667203 0.59054212 0.60591732]
  [0.95340579 0.69828869 0.08026843 0.82288405 0.13932042]]]


In [4]:
# Method 2

a = np.random.random_sample((2,3,5))
print(a)

[[[0.20587777 0.61117554 0.37344853 0.51098227 0.08707099]
  [0.41034908 0.60193015 0.72239769 0.02639518 0.44316364]
  [0.28352632 0.49492057 0.48379477 0.31128754 0.56367945]]

 [[0.08614323 0.76596331 0.5418164  0.80447033 0.4154882 ]
  [0.14427717 0.83339534 0.93440831 0.91738531 0.5518449 ]
  [0.68318666 0.73642279 0.28193266 0.33934195 0.86932768]]]


In [5]:
# Method 3

a = np.random.randint(0, 100, size=(2, 3, 5))
print(a)

[[[16 76 87 21 28]
  [63 13 36 49 71]
  [23 92 75 24 46]]

 [[67  4 69 28 50]
  [68 83 16 87  0]
  [29 23 88 15 75]]]


#### 4. Print *a*.


In [6]:
print(a)

[[[16 76 87 21 28]
  [63 13 36 49 71]
  [23 92 75 24 46]]

 [[67  4 69 28 50]
  [68 83 16 87  0]
  [29 23 88 15 75]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [12]:
if np.shape(a) == np.shape(b):
        print('Yes')
else:
        print('No')

No


#### 8. Are you able to add *a* and *b*? Why or why not?


In [14]:
c = np.add(a,b)
print(c)
#No, da error ya que 'a' y 'b' no son del mismo tamaño

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [22]:
#c = np.transpose(b)
# print(np.shape(c)) -> Transponer la función no es válido porque se necesita 2x3x5 y al transponerla devuelve 3x2x5
c = b.reshape(2, 3, 5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [25]:
d = np.add(a,c)
print(d)

#Funciona porque son del mismo tamaño

[[[17. 77. 88. 22. 29.]
  [64. 14. 37. 50. 72.]
  [24. 93. 76. 25. 47.]]

 [[68.  5. 70. 29. 51.]
  [69. 84. 17. 88.  1.]
  [30. 24. 89. 16. 76.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [31]:
print(a)
print('- - - - - - - - - - - - - - -')
print(d)
#La matriz 'd' suma 1 elemento en cada valor de los de la matriz 'a', pero además los números de la matriz 'd' son 'float'
#y los elementos de la matriz 'a' son enteros

[[[16 76 87 21 28]
  [63 13 36 49 71]
  [23 92 75 24 46]]

 [[67  4 69 28 50]
  [68 83 16 87  0]
  [29 23 88 15 75]]]
- - - - - - - - - - - - - - -
[[[17. 77. 88. 22. 29.]
  [64. 14. 37. 50. 72.]
  [24. 93. 76. 25. 47.]]

 [[68.  5. 70. 29. 51.]
  [69. 84. 17. 88.  1.]
  [30. 24. 89. 16. 76.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [33]:
e = (a*c)
print(e)

[[[16. 76. 87. 21. 28.]
  [63. 13. 36. 49. 71.]
  [23. 92. 75. 24. 46.]]

 [[67.  4. 69. 28. 50.]
  [68. 83. 16. 87.  0.]
  [29. 23. 88. 15. 75.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
#no son iguales porque los elementos de 'e' son float y los de 'a' son eneteros

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [36]:
d_max = np.max(d)
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

93.0
1.0
48.4


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [41]:
f = np.empty(shape = (2,3,5))
print(f)

[[[16. 76. 87. 21. 28.]
  [63. 13. 36. 49. 71.]
  [23. 92. 75. 24. 46.]]

 [[67.  4. 69. 28. 50.]
  [68. 83. 16. 87.  0.]
  [29. 23. 88. 15. 75.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [51]:
f = 25 * (d > d_min) * (d < d_mean) + 75 * (d < d_max) * (d > d_mean) + 0 * (d == d_min) + 100 * (d == d_max)
print(f)

[[[ 25  75  75  25  25]
  [ 75  25  25  75  75]
  [ 25 100  75  25  25]]

 [[ 75  25  75  25  75]
  [ 75  75  25  75   0]
  [ 25  25  75  25  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [50]:
print(d)
print('- - - - - - - - - - - - - - -')
print(f)

[[[17. 77. 88. 22. 29.]
  [64. 14. 37. 50. 72.]
  [24. 93. 76. 25. 47.]]

 [[68.  5. 70. 29. 51.]
  [69. 84. 17. 88.  1.]
  [30. 24. 89. 16. 76.]]]
- - - - - - - - - - - - - - -
[[[ 25  75  75  25  25]
  [ 75  25  25  75  75]
  [ 25 100  75  25  25]]

 [[ 75  25  75  25  75]
  [ 75  75  25  75   0]
  [ 25  25  75  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.